### ISSUE TITLE
When will this be done?

### ISSUE THREAD

**Issue by Xynix-the-Shadow-Hunter** [Khantober2015Saturday/Pixel-Alchemist#1]
When will this be done? I don't see any progress besides the title screen. We'll have to release it by tomorrow.

**Comment by InfinityRunner** [comment]
I have another program that I will release tomorrow. This one will be for next week.

**Comment by Xynix-the-Shadow-Hunter** [comment]
Got it.

**Comment by InfinityRunner** [comment]
K. :+1:
